<?php

namespace AppBundle\Entity;

/**
 * AppointmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointmentRepository extends \Doctrine\ORM\EntityRepository
{
    public function queryCount() {
        $dql = 'SELECT COUNT(a.id) '
            . 'FROM AppBundle:Appointment a ';

        $query = $this->getEntityManager()->createQuery($dql);


        return $query;
    }


    public function count() {

        return $this->queryCount()->getSingleScalarResult();
    }
}
